[build]
  command = "npm run netlify:build"
  publish = "dist/public"

[build.environment]
  PUPPETEER_CACHE_DIR = "/opt/build/cache/puppeteer"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/1/1/*"
  to = "/.netlify/functions/api/1/:splat"
  status = 200

[[redirects]]
  from = "/1/*"
  to = "/.netlify/functions/api/1/:splat"
  status = 200

[[redirects]]
  from = "/blog/:slug"
  to = "/blog/:slug/index.html"
  status = 200

[[redirects]]
  from = "/whats-on/:eventId"
  to = "/whats-on/:eventId/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
