/**
 * Builds the Netlify `_redirects` table.
 *
 * The goal is that the CDN answers 200 only for paths the SPA can actually
 * render, and a real 404 for everything else. Previously a single
 * `/* /index.html 200` rule meant every path on the site returned the app shell
 * with a 200, so an agent probing for resources concluded nothing was missing.
 *
 * Rules are emitted most-specific first, because Netlify applies the first match.
 */

import { PUBLIC_ROUTE_PREFIXES, PROTECTED_ROUTE_PREFIXES } from "../../shared/routes";

/**
 * Route prefixes whose children are content items rather than app screens.
 * A wildcard under these would resurrect the soft-404 problem — `/blog/anything`
 * would answer 200 — so only the children we actually published get a rule.
 */
export const DYNAMIC_CONTENT_PREFIXES = [
  "/blog",
  "/whats-on",
  "/friends-of-dzaleka",
  "/impact-report",
  "/community-hub",
] as const;

export interface RedirectOptions {
  /** Concrete routes that were prerendered, e.g. `/blog/my-post`. */
  prerenderedRoutes: string[];
}

function isDynamicChild(route: string): boolean {
  return DYNAMIC_CONTENT_PREFIXES.some((prefix) => route.startsWith(`${prefix}/`));
}

/**
 * Produce the contents of `_redirects`.
 *
 * Static files on disk still win over any 200 rule, so prerendered pages are
 * served directly; the rules below only decide what happens when no file exists.
 */
export function buildRedirects({ prerenderedRoutes }: RedirectOptions): string {
  const lines: string[] = [
    "# Generated by script/lib/redirects.ts - do not edit by hand.",
    "# Netlify applies the first matching rule, so order matters.",
    "",
    "# --- API ---------------------------------------------------------------",
    "/api/*            /.netlify/functions/api/:splat        200",
    "/1/1/*            /.netlify/functions/api/1/:splat      200",
    "/1/*              /.netlify/functions/api/1/:splat      200",
    "",
    "# --- Machine-readable files (served as static assets) -------------------",
    "# Listed so the 404 rule below can never shadow them.",
    "/llms.txt         /llms.txt                             200",
    "/openapi.json     /openapi.json                         200",
    "/sitemap.xml      /sitemap.xml                          200",
    "/robots.txt       /robots.txt                           200",
    "/.well-known/api-catalog  /.well-known/api-catalog      200",
    "",
  ];

  const seen = new Set<string>();
  const push = (from: string, to: string, status: number) => {
    const key = `${from}->${status}`;
    if (seen.has(key)) return;
    seen.add(key);
    lines.push(`${from.padEnd(17)} ${to.padEnd(37)} ${status}`);
  };

  // Concrete published content routes. These are enumerated rather than
  // wildcarded so an unknown slug still falls through to the 404 rule.
  const dynamicRoutes = prerenderedRoutes.filter(isDynamicChild).sort();
  if (dynamicRoutes.length > 0) {
    lines.push("# --- Published content items -------------------------------------------");
    for (const route of dynamicRoutes) {
      push(route, "/index.html", 200);
    }
    lines.push("");
  }

  // Listing pages for the dynamic sections: the index itself resolves, its
  // unknown children do not.
  lines.push("# --- Section index pages ------------------------------------------------");
  for (const prefix of DYNAMIC_CONTENT_PREFIXES) {
    push(prefix, "/index.html", 200);
  }
  lines.push("");

  // Everything else in the router: exact path plus its sub-routes.
  lines.push("# --- Application routes -------------------------------------------------");
  const staticPrefixes = [...PUBLIC_ROUTE_PREFIXES, ...PROTECTED_ROUTE_PREFIXES]
    .filter((prefix) => prefix !== "/")
    .filter((prefix) => !(DYNAMIC_CONTENT_PREFIXES as readonly string[]).includes(prefix))
    .sort();

  push("/", "/index.html", 200);
  for (const prefix of staticPrefixes) {
    push(prefix, "/index.html", 200);
    push(`${prefix}/*`, "/index.html", 200);
  }
  lines.push("");

  lines.push("# --- Everything else is genuinely missing -------------------------------");
  lines.push(`${"/*".padEnd(17)} ${"/404.html".padEnd(37)} 404`);
  lines.push("");

  return lines.join("\n");
}
