const GENERATED_AT = () =>
  new Intl.DateTimeFormat("en-MW", {
    dateStyle: "medium",
    timeStyle: "short",
    timeZone: "Africa/Blantyre",
  }).format(new Date());

const formatNumber = (value: number) =>
  new Intl.NumberFormat("en-MW", { maximumFractionDigits: 0 }).format(value || 0);

const formatMwk = (amount: number) =>
  new Intl.NumberFormat("en-MW", {
    style: "currency",
    currency: "MWK",
    maximumFractionDigits: 0,
  }).format(amount || 0);

function metricCard(label: string, value: string, accent: string, note: string) {
  return `
    <td class="metric-column" width="50%" style="padding: 0 8px 16px 0;">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse: separate; border-spacing: 0; background: #ffffff; border: 1px solid #dde5ee; border-radius: 10px;">
        <tr>
          <td style="padding: 18px 18px 16px;">
            <div style="height: 4px; width: 44px; border-radius: 999px; background: ${accent}; margin-bottom: 16px;"></div>
            <p style="margin: 0 0 6px; color: #64748b; font-size: 12px; font-weight: 700; letter-spacing: 0.04em; text-transform: uppercase;">${label}</p>
            <p style="margin: 0; color: #0f172a; font-size: 30px; line-height: 1.1; font-weight: 800;">${value}</p>
            <p style="margin: 8px 0 0; color: #64748b; font-size: 13px; line-height: 1.5;">${note}</p>
          </td>
        </tr>
      </table>
    </td>
  `;
}

function insightPanel(title: string, text: string, color = "#0f766e") {
  return `
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse: separate; border-spacing: 0; background: #f8fafc; border: 1px solid #dde5ee; border-left: 4px solid ${color}; border-radius: 10px; margin-top: 8px;">
      <tr>
        <td style="padding: 16px 18px;">
          <p style="margin: 0 0 4px; color: #0f172a; font-size: 14px; font-weight: 700;">${title}</p>
          <p style="margin: 0; color: #475569; font-size: 14px; line-height: 1.6;">${text}</p>
        </td>
      </tr>
    </table>
  `;
}

function emailWrapper(title: string, eyebrow: string, period: string, content: string) {
  return `
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="color-scheme" content="light">
    <title>${title}</title>
    <style>
      @media only screen and (max-width: 640px) {
        .shell { width: 100% !important; }
        .mobile-pad { padding-left: 18px !important; padding-right: 18px !important; }
        .metric-column { display: block !important; width: 100% !important; padding-right: 0 !important; }
        .header-title { font-size: 25px !important; }
      }
    </style>
  </head>
  <body style="margin: 0; padding: 0; background: #eef2f7; color: #0f172a; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;">
    <div style="display: none; max-height: 0; overflow: hidden; opacity: 0;">
      ${title} for ${period}, generated by Visit Dzaleka.
    </div>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background: #eef2f7; border-collapse: collapse;">
      <tr>
        <td align="center" style="padding: 28px 14px;">
          <table role="presentation" class="shell" width="680" cellpadding="0" cellspacing="0" style="width: 680px; max-width: 680px; border-collapse: separate; border-spacing: 0;">
            <tr>
              <td style="background: #0f172a; border-radius: 16px 16px 0 0; overflow: hidden;">
                <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
                  <tr>
                    <td class="mobile-pad" style="padding: 30px 34px 28px;">
                      <p style="margin: 0 0 12px; color: #7dd3fc; font-size: 12px; font-weight: 800; letter-spacing: 0.08em; text-transform: uppercase;">${eyebrow}</p>
                      <h1 class="header-title" style="margin: 0; color: #ffffff; font-size: 31px; line-height: 1.15; font-weight: 800;">${title}</h1>
                      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top: 18px;">
                        <tr>
                          <td style="color: #cbd5e1; font-size: 14px;">${period}</td>
                          <td align="right" style="color: #cbd5e1; font-size: 14px;">${GENERATED_AT()}</td>
                        </tr>
                      </table>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
            <tr>
              <td class="mobile-pad" style="background: #ffffff; padding: 28px 34px 34px; border-left: 1px solid #dde5ee; border-right: 1px solid #dde5ee;">
                ${content}
              </td>
            </tr>
            <tr>
              <td class="mobile-pad" style="background: #f8fafc; padding: 20px 34px; border: 1px solid #dde5ee; border-top: 0; border-radius: 0 0 16px 16px;">
                <p style="margin: 0; color: #64748b; font-size: 12px; line-height: 1.5;">
                  Visit Dzaleka Dashboard report. For live details, sign in to the admin dashboard.
                </p>
                <p style="margin: 8px 0 0; color: #94a3b8; font-size: 12px;">&copy; ${new Date().getFullYear()} Visit Dzaleka</p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>
`;
}

export function generateVisitorReport(data: { total: number; checkedIn: number; period: string }) {
  const checkInRate = data.total > 0 ? Math.round((data.checkedIn / data.total) * 100) : 0;
  const content = `
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
      <tr>
        ${metricCard("New bookings", formatNumber(data.total), "#2563eb", "Bookings created during this period.")}
        ${metricCard("Checked in", formatNumber(data.checkedIn), "#0f766e", `${checkInRate}% check-in rate for the period.`)}
      </tr>
    </table>
    ${insightPanel(
      "Operational note",
      data.total === 0
        ? "No new visitor bookings were created during this reporting window."
        : "Review upcoming bookings, guide assignment, transport needs, and visitor requirements before the next tour day.",
      "#2563eb"
    )}
  `;
  return emailWrapper("Visitor Summary", "Visitor Operations", data.period, content);
}

export function generateRevenueReport(data: { total: number; pending: number; period: string }) {
  const totalPipeline = data.total + data.pending;
  const collectedRate = totalPipeline > 0 ? Math.round((data.total / totalPipeline) * 100) : 0;
  const content = `
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
      <tr>
        ${metricCard("Collected", formatMwk(data.total), "#059669", `${collectedRate}% of active payment value is paid.`)}
        ${metricCard("Pending", formatMwk(data.pending), "#d97706", "Open payment value for non-cancelled bookings.")}
      </tr>
    </table>
    ${insightPanel(
      "Finance note",
      data.pending > 0
        ? "Follow up pending payment bookings and reconcile recent card, cash, and mobile money records."
        : "No pending payment value was recorded for this reporting window.",
      "#d97706"
    )}
  `;
  return emailWrapper("Revenue Summary", "Finance", data.period, content);
}

export function generateIncidentReport(data: { newIncidents: number; unresolved: number; period: string }) {
  const hasRisk = data.newIncidents > 0 || data.unresolved > 0;
  const content = `
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
      <tr>
        ${metricCard("New incidents", formatNumber(data.newIncidents), hasRisk ? "#dc2626" : "#0f766e", "Incidents reported during this period.")}
        ${metricCard("Unresolved", formatNumber(data.unresolved), data.unresolved > 0 ? "#dc2626" : "#0f766e", "Incidents still open or under investigation.")}
      </tr>
    </table>
    ${insightPanel(
      hasRisk ? "Security follow-up" : "Security status",
      hasRisk
        ? "Review open incidents, assign owners, and record resolution notes before closing cases."
        : "No open security follow-up was detected at the time this report was generated.",
      hasRisk ? "#dc2626" : "#0f766e"
    )}
  `;
  return emailWrapper("Security Incident Summary", "Security", data.period, content);
}
